# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  bgp_as:
    documentation_options:
      table: bgp-settings
    description: AS number to use to configure overlay when "overlay_routing_protocol" == ibgp.
    type: str
    convert_types:
      - int
