# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  mgmt_gateway:
    documentation_options:
      table: management-interface-settings
    type: str
    description: |
      OOB Management interface gateway in IPv4 format.
      Used as next-hop for default gateway or static routes defined under 'mgmt_destination_networks'.
