# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  redundancy:
    documentation_options:
      table: system-settings
    type: dict
    description: Redundancy for chassis platforms with dual supervisors | Optional.
    keys:
      protocol:
        type: str
        valid_values:
          - sso
          - rpr
