# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  terminattr_smashexcludes:
    documentation_options:
      table: cloudvision-settings
    type: str
    default: "ale,flexCounter,hardware,kni,pulse,strata"
