---
scenario:
  converge_sequence:
    - syntax
    - create
    - converge
  test_sequence:
    - syntax
    - create
    - converge
    - verify
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: DC1-LEAF1A
    image: avdteam/base:3.8-v2.0
    pre_build_image: true
    managed: false
    groups:
      - DC1_LEAF1
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit

  inventory:
    links:
      hosts: 'inventory/hosts.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --tags=generate,build
    - --skip-tags=online
    - --extra-vars
    - "avd_data_conversion_mode=error"
verifier:
  name: ansible
