hostname: cvp_instance_ip
service_routing_protocols_model: multi-agent
daemon_terminattr:
  cvaddrs:
  - 192.168.200.12:9910
  - 192.168.200.13:9910
  - 192.168.200.11:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
