---

mgmt_gateway: 192.168.200.1

node_type_keys:
  - key: spine
    type: spine
    default_evpn_role: server
    interface_descriptions:
      # Override interface description templates with our custom templates
      underlay_ethernet_interfaces: 'custom_templates/interface_descriptions/underlay/ethernet-interfaces.j2'
      underlay_port_channel_interfaces: 'custom_templates/interface_descriptions/underlay/port-channel-interfaces.j2'
      mlag_ethernet_interfaces: 'custom_templates/interface_descriptions/mlag/ethernet-interfaces.j2'
      mlag_port_channel_interfaces: 'custom_templates/interface_descriptions/mlag/port-channel-interfaces.j2'
      connected_endpoints_ethernet_interfaces: 'custom_templates/interface_descriptions/connected_endpoints/ethernet-interfaces.j2'
      connected_endpoints_port_channel_interfaces: 'custom_templates/interface_descriptions/connected_endpoints/port-channel-interfaces.j2'
      overlay_loopback_interface: 'custom_templates/interface_descriptions/loopbacks/overlay-loopback.j2'
      vtep_loopback_interface: 'custom_templates/interface_descriptions/loopbacks/vtep-loopback.j2'
  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    ip_addressing:
      # Override default ip addressing with a custom python module
      python_module: custom_ip_addressing
      python_class_name: CustomAvdIpAddressing

    interface_descriptions:
      # Override default interface description with a custom python module
      python_module: custom_interface_descriptions
      python_class_name: CustomAvdInterfaceDescriptions

ip_offset_10: 10
ip_offset_20: 20

description_prefix: "TEST_CUSTOM_PREFIX"
